// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Bootstrap():Promise<domain.Bootstrap>;

export function Connect(arg1:domain.ConnectionInput):Promise<domain.Session>;

export function ConnectSaved(arg1:number):Promise<domain.Session>;

export function Query(arg1:domain.QueryInput):Promise<domain.QueryResult>;

export function QueryHistory(arg1:number,arg2:string,arg3:string):Promise<Array<domain.QueryHistoryItem>>;

export function SaveSettings(arg1:domain.Settings):Promise<void>;
